### ISSUE TITLE
About us section

### ISSUE THREAD

**Issue by Srish-ty** [Hackodisha/Hackodisha2023#5]
About us component, which is below the hero section, containing the HO3 logo and a few paragraphs briefing about the hackathon.

**Comment by duckling69** [comment]
@Srish-ty updates?

**Comment by 8rxn** [comment]
@Srish-ty Updates

**Comment by Srish-ty** [comment]
> @Srish-ty Updates

I'm out of station, don't have pc with me. I'll complete n raise PR as soon as I get back.

**Comment by Srish-ty** [comment]
[deployed](https://deploy-preview-34--shiny-buttercream-d6e4b3.netlify.app/)

https://deploy-preview-34--shiny-buttercream-d6e4b3.netlify.app/
